<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\BrokerageMonitor.Domain\BrokerageMonitor.Domain.csproj" />
    <ProjectReference Include="..\BrokerageMonitor.Application\BrokerageMonitor.Application.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
