<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.6" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.6" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.6" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.6" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.6" />
    <PackageReference Include="MSTest" Version="4.0.2" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
    <Using Include="System.Text" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\BrokerageMonitor.Infrastructure\BrokerageMonitor.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\BrokerageMonitor.Domain\BrokerageMonitor.Domain.csproj" />
  </ItemGroup>

</Project>
